import { useEffect, useState } from "react";
import { trpc } from "@/lib/trpc";

type Settings = { enabled: boolean; automaticEnabled: boolean; gatewayConfigured: boolean; gatewayMode: "sandbox" | "production"; mpesaName: string; mpesaPhone: string; airtelName: string; airtelPhone: string; orangeName: string; orangePhone: string; afrimoneyName: string; afrimoneyPhone: string };
const emptySettings: Settings = { enabled: false, automaticEnabled: false, gatewayConfigured: false, gatewayMode: "sandbox", mpesaName: "", mpesaPhone: "", airtelName: "", airtelPhone: "", orangeName: "", orangePhone: "", afrimoneyName: "", afrimoneyPhone: "" };
const fc = (value: number) => `${new Intl.NumberFormat("fr-FR").format(Number(value))} FC`;
const providerName = (provider: "orange" | "airtel" | "afrimoney" | "mpesa") => ({ orange: "Orange Money", airtel: "Airtel Money", afrimoney: "AfriMoney", mpesa: "M-Pesa" }[provider]);
const statusName: Record<string, string> = { pending: "À vérifier", awaiting_payment: "Paiement acheteur en cours", payout_pending: "Versement vendeur en cours", approved: "Validé", rejected: "Refusé", refund_required: "Remboursement à faire", refunded: "Remboursé" };

export default function AdminPaymentPanel({ isOwner }: { isOwner: boolean }) {
  const utils = trpc.useUtils();
  const overview = trpc.admin.paymentOverview.useQuery(undefined, { retry: false });
  const [settings, setSettings] = useState<Settings>(emptySettings);
  const [payoutReferences, setPayoutReferences] = useState<Record<string, string>>({});
  const [notice, setNotice] = useState("");
  useEffect(() => { if (overview.data?.settings) setSettings({ ...emptySettings, ...overview.data.settings, mpesaName: overview.data.settings.mpesaName ?? "", mpesaPhone: overview.data.settings.mpesaPhone ?? "", airtelName: overview.data.settings.airtelName ?? "", airtelPhone: overview.data.settings.airtelPhone ?? "" }); }, [overview.data?.settings]);
  const refresh = async () => { await Promise.all([utils.admin.paymentOverview.invalidate(), utils.admin.overview.invalidate()]); };
  const configure = trpc.admin.configurePayments.useMutation({ onSuccess: async (next) => { setSettings({ ...emptySettings, ...next, mpesaName: next.mpesaName ?? "", mpesaPhone: next.mpesaPhone ?? "", airtelName: next.airtelName ?? "", airtelPhone: next.airtelPhone ?? "", orangeName: next.orangeName ?? "", orangePhone: next.orangePhone ?? "", afrimoneyName: next.afrimoneyName ?? "", afrimoneyPhone: next.afrimoneyPhone ?? "" }); setNotice(next.enabled ? "Les moyens Mobile Money manuels sont activés." : "Les commandes sont en pause."); await refresh(); }, onError: (e) => setNotice(e.message) });
  const reviewPayment = trpc.admin.reviewPayment.useMutation({ onSuccess: async (result) => { setNotice(result.status === "approved" ? "Paiement vérifié : portefeuille vendeur et commission 5 % crédités." : result.status === "rejected" ? "Paiement refusé; le stock a été libéré." : result.status === "refund_required" ? "Remboursement marqué à effectuer par transfert manuel." : "Remboursement confirmé manuellement; stock libéré."); await refresh(); }, onError: (e) => setNotice(e.message) });
  const reviewPayout = trpc.admin.reviewPayout.useMutation({ onSuccess: async (result) => { setNotice(result.status === "paid" ? "Retrait marqué payé; le solde vendeur a été débité." : "Demande de retrait refusée; le solde demeure disponible."); await refresh(); }, onError: (e) => setNotice(e.message) });
  const payments = overview.data?.paymentRequests ?? [];
  const payouts = overview.data?.payoutRequests ?? [];
  const pendingPayments = payments.filter((payment) => ["pending", "awaiting_payment", "payout_pending"].includes(payment.status));
  const pendingPayouts = payouts.filter((payout) => payout.status === "pending");

  return <section className="adm-card adm-payments" aria-labelledby="adm-payments-title">
    <div className="adm-card-heading"><div><span className="adm-eyebrow">MOBILE MONEY · RAPPROCHEMENT</span><h2 id="adm-payments-title">Commandes, commissions et retraits</h2></div><span className={`adm-payment-state ${settings.enabled ? "on" : "off"}`}>{settings.enabled ? "MANUEL" : "EN PAUSE"}</span></div>
    {overview.isLoading ? <p className="adm-note">Chargement du registre…</p> : overview.error ? <p className="adm-error">{overview.error.message}</p> : <>
      <div className="adm-money-summary"><article><small>COMMISSION AGRONEX CONFIRMÉE</small><b>{fc(overview.data?.commissions ?? 0)}</b><span>5 % des paiements acheteurs confirmés</span></article><article><small>PAIEMENTS EN COURS</small><b>{pendingPayments.length}</b><span>Statuts vérifiés par référence fournisseur</span></article><article><small>VERSEMENTS MANUELS EN ATTENTE</small><b>{pendingPayouts.length}</b><span>À exécuter depuis le téléphone marchand</span></article></div>
      <div className="adm-payment-warning"><b>Mode sécurisé :</b> les quatre opérateurs sont préparés côté serveur mais aucune API ni transaction n’est activée. Les paiements manuels restent en pause jusqu’à activation explicite.</div>
      
      {isOwner ? <form className="adm-money-settings" onSubmit={(event) => { event.preventDefault(); if (settings.enabled && !settings.mpesaPhone.trim() && !settings.airtelPhone.trim() && !settings.orangePhone.trim() && !settings.afrimoneyPhone.trim()) { setNotice("Ajoute au moins un compte marchand de réception avant d’activer le mode manuel."); return; } configure.mutate({ enabled: settings.enabled, automaticEnabled: false, mpesaName: settings.mpesaName, mpesaPhone: settings.mpesaPhone, airtelName: settings.airtelName, airtelPhone: settings.airtelPhone, orangeName: settings.orangeName, orangePhone: settings.orangePhone, afrimoneyName: settings.afrimoneyName, afrimoneyPhone: settings.afrimoneyPhone }); }}>
        <div><span className="adm-eyebrow">CONFIGURATION RÉSERVÉE AU PROPRIÉTAIRE</span><h3>Modes Mobile Money</h3><p>Les secrets API ne sont jamais enregistrés dans cette page ni exposés au navigateur; ils restent côté serveur et tous les opérateurs sont désactivés par défaut.</p></div>
        <div className="adm-money-fields"><fieldset><legend>M-Pesa · mode manuel de secours</legend><label>Nom du bénéficiaire<input value={settings.mpesaName} onChange={(e) => setSettings((old) => ({ ...old, mpesaName: e.target.value }))} maxLength={100} placeholder="AGRONEX" /></label><label>Numéro de réception<input type="tel" value={settings.mpesaPhone} onChange={(e) => setSettings((old) => ({ ...old, mpesaPhone: e.target.value }))} maxLength={48} placeholder="ex. 0812345678" /></label></fieldset><fieldset><legend>Airtel Money · mode manuel de secours</legend><label>Nom du bénéficiaire<input value={settings.airtelName} onChange={(e) => setSettings((old) => ({ ...old, airtelName: e.target.value }))} maxLength={100} placeholder="AGRONEX" /></label><label>Numéro de réception<input type="tel" value={settings.airtelPhone} onChange={(e) => setSettings((old) => ({ ...old, airtelPhone: e.target.value }))} maxLength={48} placeholder="ex. 0991234567" /></label></fieldset><fieldset><legend>Orange Money · mode manuel</legend><label>Nom du bénéficiaire<input value={settings.orangeName} onChange={(e) => setSettings((old) => ({ ...old, orangeName: e.target.value }))} maxLength={100} placeholder="AGRONEX" /></label><label>Numéro de réception<input type="tel" value={settings.orangePhone} onChange={(e) => setSettings((old) => ({ ...old, orangePhone: e.target.value }))} maxLength={48} placeholder="ex. 0891234567" /></label></fieldset><fieldset><legend>AfriMoney · mode manuel</legend><label>Nom du bénéficiaire<input value={settings.afrimoneyName} onChange={(e) => setSettings((old) => ({ ...old, afrimoneyName: e.target.value }))} maxLength={100} placeholder="AGRONEX" /></label><label>Numéro de réception<input type="tel" value={settings.afrimoneyPhone} onChange={(e) => setSettings((old) => ({ ...old, afrimoneyPhone: e.target.value }))} maxLength={48} placeholder="Numéro marchand" /></label></fieldset></div>
        <label className="adm-money-toggle"><input type="checkbox" checked={settings.enabled} onChange={(e) => setSettings((old) => ({ ...old, enabled: e.target.checked }))} /> Ouvrir le mode manuel de secours</label>
        <button className="adm-money-primary" type="submit" disabled={configure.isPending}>{configure.isPending ? "Enregistrement…" : "Enregistrer la configuration"}</button>
      </form> : <p className="adm-note">La configuration des comptes marchands et l’activation des commandes restent réservées au propriétaire de la plateforme.</p>}
      {notice && <p className="adm-money-notice" role="status">{notice}</p>}

      <div className="adm-money-queue"><div className="adm-card-heading"><div><span className="adm-eyebrow">SUIVI</span><h3>Paiements acheteurs</h3></div><span className="adm-activity-count">{pendingPayments.length} en cours</span></div>
        {!payments.length ? <div className="adm-empty"><span>◈</span><p>Aucun paiement enregistré.</p></div> : payments.map((payment) => <article className="adm-money-row" key={payment.id}>
          <div className="adm-money-identity"><span className={`adm-wallet-status ${payment.status}`}>{statusName[payment.status] || payment.status}</span><b>{payment.postTitle}</b><small>{payment.buyerName} → {payment.farmerName} · {providerName(payment.provider)} · {"manuel"} · {new Date(payment.createdAt).toLocaleString("fr-FR")}</small><small>Destination : {payment.destinationName ?? "Compte AGRONEX"} · {payment.destinationPhone ?? "numéro non mémorisé"}</small><small>Référence : <strong>{payment.reference.startsWith("PENDING-") ? "Non encore saisie par l’acheteur" : payment.reference}</strong></small>{payment.failureNote && <small className="adm-money-note">{payment.failureNote}</small>}</div>
          <div className="adm-money-values"><b>{fc(Number(payment.grossAmount))}</b><small>5 % : {fc(Number(payment.commissionAmount))}</small><small>95 % vendeur : {fc(Number(payment.farmerAmount))}</small></div>
          {payment.status === "pending" && payment.reference !== `PENDING-${payment.id}` && <div className="adm-money-actions"><button className="adm-money-primary" type="button" onClick={() => { if (window.confirm(`As-tu vérifié la réception réelle de ${fc(Number(payment.grossAmount))} et la référence ${payment.reference} sur ton téléphone?`)) reviewPayment.mutate({ paymentId: payment.id, decision: "approve", note: "Réception vérifiée manuellement sur le téléphone opérateur." }); }} disabled={reviewPayment.isPending}>Vérifier et créditer 95/5</button><button className="adm-money-danger" type="button" onClick={() => { const note = window.prompt("Motif du refus (ou vide) :") ?? ""; if (window.confirm("Confirme qu’aucun transfert n’a été reçu. Le stock sera libéré.")) reviewPayment.mutate({ paymentId: payment.id, decision: "reject", note }); }}>Refuser · aucun transfert</button><button className="adm-money-danger" type="button" onClick={() => { if (window.confirm("As-tu bien reçu l’argent mais dois-tu le rembourser hors plateforme?")) reviewPayment.mutate({ paymentId: payment.id, decision: "refund_required", note: "Remboursement demandé; transfert retour à effectuer manuellement." }); }}>Remboursement à faire</button></div>}
          {payment.status === "pending" && payment.reference === `PENDING-${payment.id}` && <div className="adm-pay-pending">En attente de la référence du transfert; ne pas créditer.<button className="adm-money-danger" type="button" onClick={() => { if (window.confirm("Confirmer que l’acheteur n’a pas effectué de transfert?")) reviewPayment.mutate({ paymentId: payment.id, decision: "reject", note: "Demande non finalisée; transfert non constaté." }); }}>Annuler la réservation non finalisée</button></div>}
          {payment.status === "payout_pending" && <div className="adm-pay-pending">Encaissement reçu; versement B2C au vendeur en cours de vérification par référence.</div>}
          {payment.status === "refund_required" && <button className="adm-money-primary" type="button" onClick={() => { if (window.confirm("Confirmer que le remboursement a réellement été transféré au client?")) reviewPayment.mutate({ paymentId: payment.id, decision: "refunded", note: "Remboursement effectué manuellement et vérifié." }); }}>Confirmer le remboursement fait</button>}
        </article>)}
      </div>

      <div className="adm-money-queue"><div className="adm-card-heading"><div><span className="adm-eyebrow">VERSEMENTS VENDEURS</span><h3>Transferts Mobile Money</h3></div><span className="adm-activity-count">{pendingPayouts.length} en attente</span></div>
        {!payouts.length ? <div className="adm-empty"><span>↗</span><p>Aucune demande de retrait.</p></div> : payouts.map((payout) => <article className="adm-money-row" key={payout.id}>
          <div className="adm-money-identity"><span className={`adm-wallet-status ${payout.status}`}>{payout.status === "pending" ? ("À transférer") : payout.status === "paid" ? "Payé" : "Échec / refusé"}</span><b>{payout.farmerName}</b><small>{providerName(payout.provider)} · vers {payout.phone} · {"retrait manuel"} · {new Date(payout.requestedAt).toLocaleString("fr-FR")}</small>{payout.payoutReference && <small>Référence de versement : {payout.payoutReference}</small>}{payout.note && <small className="adm-money-note">{payout.note}</small>}</div>
          <div className="adm-money-values"><b>{fc(Number(payout.amount))}</b></div>
          {payout.status === "pending" && <div className="adm-money-actions"><label>Référence de l’envoi<input value={payoutReferences[payout.id] ?? ""} onChange={(e) => setPayoutReferences((old) => ({ ...old, [payout.id]: e.target.value }))} placeholder="SMS M-Pesa/Airtel" maxLength={120} /></label><button className="adm-money-primary" type="button" disabled={reviewPayout.isPending || (payoutReferences[payout.id] ?? "").trim().length < 3} onClick={() => { if (window.confirm(`As-tu envoyé ${fc(Number(payout.amount))} à ${payout.phone} et vérifié le SMS?`)) reviewPayout.mutate({ payoutId: payout.id, decision: "paid", reference: payoutReferences[payout.id] ?? "", note: "Transfert Mobile Money exécuté et vérifié manuellement." }); }}>Marquer comme payé</button><button className="adm-money-danger" type="button" onClick={() => { const note = window.prompt("Motif du refus (ou vide) :") ?? ""; if (window.confirm("Refuser la demande? Le solde restera disponible.")) reviewPayout.mutate({ payoutId: payout.id, decision: "reject", reference: "", note }); }}>Refuser la demande</button></div>}
        </article>)}
      </div>
    </>}
  </section>;
}
